# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vue.js CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: export NVM_DIR=/home/dev/.nvm && source /home/dev/.nvm/nvm.sh && cd /home/dev/actions-runner2/_work/b2c-FE/b2c-FE && npm install && npm run build:dev
      - run: sudo rm -rf /var/www/html/dist2
      - run: sudo mkdir /var/www/html/dist2
      - run: sudo cp -R /home/dev/actions-runner2/_work/b2c-FE/b2c-FE/dist/* /var/www/html/dist2
      - run: sudo systemctl restart nginx
